services:
  webserver:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/certs/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    deploy:
      mode: global
      replicas: 0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/certs/:/etc/letsencrypt/:rw

  zarinbyte_backend:
    image: ghcr.io/imanhpr/zarinbyte-backend:${COMMIT_HASH}
    restart: always
    deploy:
      mode: replicated
      replicas: 2

    environment:
      - MIKRO_ORM_DB_HOST=pg-db
      - MIKRO_ORM_DB_PORT=5432
      - MIKRO_ORM_DB_NAME=zarsad-db
      - MIKRO_ORM_DB_PASSWORD=testpass
      - MIKRO_ORM_DB_USER=postgres
      - NODE_ENV=production
      - APP_PORT=3007
      - npm_package_version=${npm_package_version}
    depends_on:
      - pg-db

  pg-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=zarsad-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zarsad-db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

