# syntax=docker/dockerfile:1
# check=skip=SecretsUsedInArgOrEnv
FROM node:22-slim

WORKDIR /app

COPY package*.json .
COPY ./packages/backend/package.json ./packages/backend/package.json

RUN npm ci -w packages/backend
COPY ./packages/backend/ ./packages/backend/

CMD [ "npx" , "-w" , "packages/backend" , "mikro-orm-esm" , "migration:up" ]