/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as InvoiceTransactionIdImport } from './routes/invoice.$transactionId'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as AuthRegisterIndexImport } from './routes/auth/register.index'
import { Route as AuthLoginIndexImport } from './routes/auth/login.index'
import { Route as AuthMethodVerifyImport } from './routes/auth/$method.verify'
import { Route as LayoutReportTransactionIdIndexImport } from './routes/_layout/report/transaction.$id.index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const InvoiceTransactionIdRoute = InvoiceTransactionIdImport.update({
  id: '/invoice/$transactionId',
  path: '/invoice/$transactionId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthMethodVerifyRoute = AuthMethodVerifyImport.update({
  id: '/auth/$method/verify',
  path: '/auth/$method/verify',
  getParentRoute: () => rootRoute,
} as any)

const LayoutReportTransactionIdIndexRoute =
  LayoutReportTransactionIdIndexImport.update({
    id: '/report/transaction/$id/',
    path: '/report/transaction/$id/',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/invoice/$transactionId': {
      id: '/invoice/$transactionId'
      path: '/invoice/$transactionId'
      fullPath: '/invoice/$transactionId'
      preLoaderRoute: typeof InvoiceTransactionIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/auth/$method/verify': {
      id: '/auth/$method/verify'
      path: '/auth/$method/verify'
      fullPath: '/auth/$method/verify'
      preLoaderRoute: typeof AuthMethodVerifyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/report/transaction/$id/': {
      id: '/_layout/report/transaction/$id/'
      path: '/report/transaction/$id'
      fullPath: '/report/transaction/$id'
      preLoaderRoute: typeof LayoutReportTransactionIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutReportTransactionIdIndexRoute: typeof LayoutReportTransactionIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutReportTransactionIdIndexRoute: LayoutReportTransactionIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/invoice/$transactionId': typeof InvoiceTransactionIdRoute
  '/': typeof LayoutIndexRoute
  '/auth/$method/verify': typeof AuthMethodVerifyRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/report/transaction/$id': typeof LayoutReportTransactionIdIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/invoice/$transactionId': typeof InvoiceTransactionIdRoute
  '/': typeof LayoutIndexRoute
  '/auth/$method/verify': typeof AuthMethodVerifyRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/report/transaction/$id': typeof LayoutReportTransactionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/invoice/$transactionId': typeof InvoiceTransactionIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/auth/$method/verify': typeof AuthMethodVerifyRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_layout/report/transaction/$id/': typeof LayoutReportTransactionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/invoice/$transactionId'
    | '/'
    | '/auth/$method/verify'
    | '/auth/login'
    | '/auth/register'
    | '/report/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/invoice/$transactionId'
    | '/'
    | '/auth/$method/verify'
    | '/auth/login'
    | '/auth/register'
    | '/report/transaction/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/invoice/$transactionId'
    | '/_layout/'
    | '/auth/$method/verify'
    | '/auth/login/'
    | '/auth/register/'
    | '/_layout/report/transaction/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  InvoiceTransactionIdRoute: typeof InvoiceTransactionIdRoute
  AuthMethodVerifyRoute: typeof AuthMethodVerifyRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  InvoiceTransactionIdRoute: InvoiceTransactionIdRoute,
  AuthMethodVerifyRoute: AuthMethodVerifyRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/invoice/$transactionId",
        "/auth/$method/verify",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/",
        "/_layout/report/transaction/$id/"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/invoice/$transactionId": {
      "filePath": "invoice.$transactionId.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/auth/$method/verify": {
      "filePath": "auth/$method.verify.tsx"
    },
    "/auth/login/": {
      "filePath": "auth/login.index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register.index.tsx"
    },
    "/_layout/report/transaction/$id/": {
      "filePath": "_layout/report/transaction.$id.index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
