export enum CurrencyTypeEnum {
  MELTED_GOLD_NAGHDI_18 = "MELTED_GOLD_NAGHDI_18",
  MELTED_GOLD_BONAK_18 = "MELTED_GOLD_BONAK_18",
  MELTED_GOLD_LOWER_18 = "MELTED_GOLD_LOWER_18",
  TOMAN = "TOMAN",
  MELTED_GOLD_18 = "MELTED_GOLD_18",
}
