name: "Seed database"
run-name: "Seed database"

on: workflow_dispatch

jobs:
  run_db_seeder:
    name: Seed postgres db
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote host to run migration
        uses: appleboy/ssh-action@v1
        with:
          key: ${{ secrets.MANAGER_SWARM_PRIVATE_KEY }}
          host: ${{ secrets.MANAGER_SWARM_HOST }}
          username: ${{ vars.MANAGER_SWARM_USER }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker service create --network test-zarinbyte_default --name db-migration --mode replicated-job --replicas 1 \
            --restart-condition=none -e MIKRO_ORM_DB_USER=${{ secrets.MIKRO_ORM_DB_USER }} \
            -e MIKRO_ORM_DB_PASSWORD=${{ secrets.MIKRO_ORM_DB_PASSWORD }} \
            -e MIKRO_ORM_DB_NAME=${{ vars.MIKRO_ORM_DB_NAME }} \
            -e MIKRO_ORM_DB_PORT=${{ vars.MIKRO_ORM_DB_PORT }} \
            -e MIKRO_ORM_DB_HOST=${{ vars.MIKRO_ORM_DB_HOST }} \
            --entrypoint "sh ./packages/backend/db-seed.sh" \
            ghcr.io/${{ github.actor }}/zarinbyte-db-migration:latest
