name: "Deploy zarinbyte backend"
run-name: "${{ github.action }} deplys to zarinbyte backend cluster"

on: workflow_dispatch

permissions:
  packages: read

jobs:
  deploy_to_swarm:
    runs-on: ubuntu-latest
    env:
      COMMIT_HASH: latest
    steps:
      - name: SSH into remote host
        uses: appleboy/ssh-action@v1
        with:
          key: ${{ secrets.MANAGER_SWARM_PRIVATE_KEY }}
          host: ${{ secrets.MANAGER_SWARM_HOST }}
          username: ${{ vars.MANAGER_SWARM_USER }}
          script: |
            cd zarinbyte
            export COMMIT_HASH=${{ env.COMMIT_HASH }}
            docker stack deploy -c compose.yml test-zarinbyte
