name: zarinbyte backend build
run-name: build and push zarinbyte backend

on: workflow_dispatch

permissions:
  packages: write

env:
  container_tag: ${{ github.sha }}

jobs:
  build_and_push:
    name: print hello job
    runs-on: ubuntu-latest

    steps:
      - name: "Login to github packages"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "ghcr.io/${{ github.actor }}/zarinbyte-backend:${{ github.sha }}"
          file: "./Dockerfile.backend"

      - name: db migration cache
        id: db-migration-cache
        uses: actions/cache@v4
        with:
          path: db-migration-cache
          key: ${{ hashFiles('packages/backend/src/models') }}

      - name: build migration image
        if: steps.db-migration-cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            "ghcr.io/${{ github.actor }}/zarinbyte-db-migration:${{ github.sha }}"
            "ghcr.io/${{ github.actor }}/zarinbyte-db-migration:latest"
