name: zarinbyte backend build
run-name: build and push zarinbyte backend

on: workflow_dispatch

env:
  container_tag: ${{ github.sha }}

jobs:
  build_and_push:
    permissions:
      packages: write
    name: print hello job
    runs-on: ubuntu-latest

    steps:
      - name: "Login to github packages"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "ghcr.io/${{ github.actor }}/zarinbyte-backend:${{ github.sha }}"
          file: "./Dockerfile.backend"

      - name: db migration cache
        id: db-migration-cache
        uses: actions/cache@v4
        with:
          path: db-migration-cache
          key: db-migration-cache-${{ hashFiles('packages/backend/src/models/**') }}
          restore-keys: |
            db-migration-cache-

      - name: build migration image
        if: steps.db-migration-cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          target: "migrate_build"
          file: "./Dockerfile.backend"
          tags: |
            "ghcr.io/${{ github.actor }}/zarinbyte-db-migration:${{ github.sha }}"
            "ghcr.io/${{ github.actor }}/zarinbyte-db-migration:latest"

  deploy_to_swarm:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    env:
      COMMIT_HASH: ${{ github.sha }}
    steps:
      - name: SSH into remote host
        uses: appleboy/ssh-action@v1
        with:
          key: ${{ secrets.MANAGER_SWARM_PRIVATE_KEY }}
          host: ${{ secrets.MANAGER_SWARM_HOST }}
          username: ${{ vars.MANAGER_SWARM_USER }}
          script: |
            cd zarinbyte
            export COMMIT_HASH=${{ env.COMMIT_HASH }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stack deploy -c compose.yml test-zarinbyte
            docker logout ghcr.io
